### ISSUE TITLE
boot16.asm fails to load a FAT larger than 64KB because of ReadSector overflows.

### ISSUE THREAD

**Issue by tazgm** [alexfru/BootProg#1]
The patch http://mirror1.slitaz.org/boot/BootProg/BootProg-v1.5.U fix it.

BTW: Enhanced boot16.asm and boot32.asm with better error messages are
available in http://mirror1.slitaz.org/boot/BootProg/

boot16.asm supports a 8086 cpu, 8GB HD, detects the disk geometry, can load
larger .EXE files and is merged with boot12.asm (FAT12 and FAT16 support).

boot32.asm has a LBA (max 4TB) and CHS (max 8GB) driver with retries.

A tiny shell installer is also available:
http://mirror1.slitaz.org/boot/BootProg/bootprog

**Comment by alexfru** [comment]
@tazgm Thanks! I'll review the code and see if or how I'll incorporate the changes. Likely, it won't be soon though.

**Comment by tazgm** [comment]
Update: http://mirror1.slitaz.org/boot/BootProg/boot16.asm has a new LBA (max 2TB) and CHS (max 8GB).

**Comment by alexfru** [comment]
For the time being I only fixed the original bug with loading FAT16 larger than 64KB.

Still unsure if or when I'm gonna make other improvements.
- Querying disk geometry from BIOS is kinda important (I just ran into this problem when testing the fix for large FAT16).
- 8086 in FAT12 and FAT16 is nice.
- Longer error messages are nice.
- Merging/unifying FAT12 and FAT16 is OK at source code level, but unnecessary in the binary.
- CHS-based FAT32... I'd probably pass on it.

**Comment by alexfru** [comment]
@tazgm Some of the improvements are in.

**Comment by tazgm** [comment]
Need to had Exfat support ?

SliTaz provides exfat support with the file bootex.asm in
https://hg.slitaz.org/wok/file/tip/BootProg/stuff
The compile rules are in
https://hg.slitaz.org/wok/file/tip/BootProg/receipt to build
https://cook.slitaz.org/index.cgi?files=BootProg
Assembly listing is
https://cook.slitaz.org/index.cgi?stuff=../wok/BootProg/source/BootProg-slitaz/bootex.lst

It may load up to 511 extra bytes in memory (1 sector only, the maximum
cluster size is 32MB)
It can run up to 637KB programs with AX=FFFF according to
https://wiki.osdev.org/MZ#Initial_Program_State and an empty cmdline.

Regards,

Pascal
